name: Build LaTeX document
on:
  push:
    tags:
      - "v*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "main.tex"
          post_compile: mv "main.pdf" "${{ github.event.repository.name }}.pdf"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ github.event.repository.name }}.pdf"
