name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      - name: Install copier
        run: python -m pip install copier
      - name: Generate template
        run: copier copy . build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/00README.XXX
            build/*.sty
            build/*.tex
            build/*.cls
